//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    using QuanLyKho.ViewModel;

    public partial class Customer : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OutputInfoes = new HashSet<OutputInfo>();
        }

        private int _Id_Customer;
        public int Id_Customer { get => _Id_Customer; set { _Id_Customer = value; OnPropertyChanged(); } }

        private string _DisplayName_Customer;
        public string DisplayName_Customer { get => _DisplayName_Customer; set { _DisplayName_Customer = value; OnPropertyChanged(); } }

        private string _Phone_Customer;
        public string Phone_Customer { get => _Phone_Customer; set { _Phone_Customer = value; OnPropertyChanged(); } }

        private string _Address_Customer;
        public string Address_Customer { get => _Address_Customer; set { _Address_Customer = value; OnPropertyChanged(); } }

        private string _Email_Customer;
        public string Email_Customer { get => _Email_Customer; set { _Email_Customer = value; OnPropertyChanged(); } }

        private string _MoreInfo_Customer;
        public string MoreInfo_Customer { get => _MoreInfo_Customer; set { _MoreInfo_Customer = value; OnPropertyChanged(); } }
        public Nullable<System.DateTime> ContractDate_Customer { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfoes { get; set; }
    }
}
