//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class InputInfo
    {
        public string Id_InputInfo { get; set; }
        public string Id_Object { get; set; }
        public string Id_Input { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<double> Price_Input { get; set; }
        public Nullable<double> Price_Output { get; set; }
        public string Status_InputInfo { get; set; }
    
        public virtual Input Input { get; set; }
        public virtual Object Object { get; set; }
    }
}
