//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    using QuanLyKho.ViewModel;

    public partial class Object : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Object()
        {
            this.InputInfoes = new HashSet<InputInfo>();
            this.OutputInfoes = new HashSet<OutputInfo>();
        }

        private string _Id_Object;
        public string Id_Object { get => _Id_Object; set { _Id_Object = value; OnPropertyChanged(); } }
        private string _DisplayName_Object;
        public string DisplayName_Object { get => _DisplayName_Object; set { _DisplayName_Object = value; OnPropertyChanged(); } }

        private int _Id_Unit;
        public int Id_Unit { get => _Id_Unit; set { _Id_Unit = value; OnPropertyChanged(); } }

        private int _Id_Suplier;
        public int Id_Suplier { get => _Id_Suplier; set { _Id_Suplier = value; OnPropertyChanged(); } }

        private string _QRCode_Object;
        public string QRCode { get => _QRCode_Object; set { _QRCode_Object = value; OnPropertyChanged(); } }

        private string _BarCode_Object;
        public string BarCode { get => _BarCode_Object; set { _BarCode_Object = value; OnPropertyChanged(); } }




        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InputInfo> InputInfoes { get; set; }

        private Unit _Unit;
        public virtual Unit Unit { get => _Unit; set { _Unit = value; OnPropertyChanged(); } }

        private Suplier _Suplier;
        public virtual Suplier Suplier { get => _Suplier; set { _Suplier = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OutputInfo> OutputInfoes { get; set; }
    }
}
