//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutputInfo
    {
        public string Id_OutputInfo { get; set; }
        public string Id_Object { get; set; }
        public string Id_Output { get; set; }
        public int Id_Customer { get; set; }
        public Nullable<int> Count { get; set; }
        public string Status_OutputInfo { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Object Object { get; set; }
        public virtual Output Output { get; set; }
    }
}
