//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyKho.Model
{
    using System;
    using System.Collections.Generic;
    using QuanLyKho.ViewModel;

    public partial class UserRole : BaseViewModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRole()
        {
            this.Users = new HashSet<User>();
        }
    
        //public int Id_UserRole { get; set; }
        private int _Id_UserRole;
        public int Id_UserRole { get => _Id_UserRole; set { _Id_UserRole = value; OnPropertyChanged(); } }
        //public string DisplayName_UserRole { get; set; }
        private string _DisplayName_UserRole;
        public string DisplayName_UserRole { get => _DisplayName_UserRole; set { _DisplayName_UserRole = value; OnPropertyChanged(); } }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
